name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the Docker image
      env:
        TAG_NAME: $(date +%s)
      run: docker build . --file Docker/Dockerfile --tag ${{secrets.DOCKER_USER}}/hazelcast-bucket4j:$TAG_NAME
    
    - name: Docker push
      run: docker push ${{secrets.DOCKER_USER}}/hazelcast-bucket4j:$TAG_NAME
